name: chembl-beaker
channels:
- rdkit
- defaults
dependencies:
- blas=1.0=mkl
- bzip2=1.0.6=3
- cairo=1.14.8=0
- certifi=2016.2.28=py27_0
- fontconfig=2.12.1=3
- freetype=2.5.5=2
- jbig=2.1=0
- jpeg=9b=0
- libiconv=1.14=0
- libpng=1.6.30=1
- libtiff=4.0.6=3
- libxml2=2.9.4=0
- mkl=2017.0.3=0
- numpy=1.13.1=py27_0
- olefile=0.44=py27_0
- openssl=1.0.2l=0
- pandas=0.20.3=py27_0
- pillow=4.2.1=py27_0
- pip=9.0.1=py27_1
- pixman=0.34.0=0
- python=2.7.13=0
- python-dateutil=2.6.1=py27_0
- pytz=2017.2=py27_0
- readline=6.2=2
- setuptools=36.4.0=py27_1
- six=1.10.0=py27_0
- sqlite=3.13.0=0
- tk=8.5.18=0
- wheel=0.29.0=py27_0
- xz=5.2.3=0
- zlib=1.2.11=0
- boost=1.63.0=py27_1
- rdkit=2017.09.3.0=py27_1
prefix: /Users/jfmosquera/miniconda3/envs/chembl-beaker

